# Base configuration for AIQuantum
general:
  project_name: "AIQuantum"
  version: "0.1.0"
  environment: "development"

# Exchange Configuration
exchange:
  name: binanceus
  type: spot
  api_key: ${BINANCEUS_API_KEY}
  api_secret: ${BINANCEUS_API_SECRET}
  testnet: false
  rate_limit: true
  timeout: 30000
  options:
    defaultType: spot
    adjustForTimeDifference: true
    recvWindow: 60000

# Data Configuration
data:
  directory: data/
  cache:
    enabled: true
    directory: data/cache/
    expiration: 3600  # seconds
  formats:
    - csv
    - parquet
  timeframes:
    - 1m
    - 5m
    - 15m
    - 1h
    - 4h
    - 1d
  source: "binance"
  symbols: ["BTC/USDT", "ETH/USDT"]
  timeframe: "1h"
  lookback_days: 30

# Trading Configuration
trading:
  mode: "paper"
  paper_balance: 10000.0
  live_api_key: ""
  live_api_secret: ""
  symbols:
    - BTC/USDT
    - ETH/USDT
    - BNB/USDT
  default_symbol: BTC/USDT
  default_timeframe: 1h
  position_size: 0.1  # 10% of portfolio
  max_positions: 3
  leverage: 1.0  # No leverage for spot trading

# Risk Management
risk:
  max_drawdown: 0.2  # 20%
  stop_loss: 0.05   # 5%
  take_profit: 0.1  # 10%
  max_position_size: 0.2  # 20% of portfolio
  risk_per_trade: 0.02  # 2% of portfolio
  max_daily_loss: 0.02

# Technical Analysis
technical:
  indicators:
    - sma
    - ema
    - rsi
    - macd
    - bollinger
  default_periods:
    sma: [20, 50, 200]
    ema: [12, 26, 50]
    rsi: 14
    macd: [12, 26, 9]
    bollinger: [20, 2]

# Machine Learning
ml:
  sequence_length: 60
  train_test_split: 0.8
  validation_split: 0.1
  batch_size: 32
  epochs: 100
  early_stopping:
    patience: 10
    min_delta: 0.001

# Logging
logging:
  level: INFO
  file: logs/aiquantum.log
  max_size: 10485760  # 10MB
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Monitoring
monitoring:
  enabled: true
  interval: 300  # seconds
  metrics:
    - performance
    - risk
    - positions
    - orders
  alerts:
    email: ${ALERT_EMAIL}
    slack: ${SLACK_WEBHOOK}

strategy:
  enabled_strategies:
    - "rsi"
    - "ema"
    - "lstm"
  default_strategy: "lstm" 