# Base configuration for AIQuantum
general:
  project_name: "AIQuantum"
  version: "0.1.0"
  environment: "development"

data:
  source: "binance"
  symbols: ["BTC/USDT", "ETH/USDT"]
  timeframe: "1h"
  lookback_days: 30

strategy:
  enabled_strategies:
    - "rsi"
    - "ema"
    - "lstm"
  default_strategy: "lstm"

risk:
  max_position_size: 0.1
  max_daily_loss: 0.02
  max_drawdown: 0.1

trading:
  mode: "paper"
  paper_balance: 10000.0
  live_api_key: ""
  live_api_secret: ""

logging:
  level: "INFO"
  file: "logs/aiquantum.log"
  max_size: 10485760  # 10MB
  backup_count: 5 