# Risk management configuration
position_sizing:
  max_position_size: 0.1
  min_position_size: 0.01
  position_size_increment: 0.01

risk_limits:
  max_daily_loss: 0.02
  max_drawdown: 0.1
  max_leverage: 1.0
  max_open_positions: 3

stop_loss:
  trailing_stop: true
  trailing_stop_distance: 0.02
  hard_stop_loss: 0.05

risk_metrics:
  var_confidence: 0.95
  var_lookback_days: 30
  max_correlation: 0.7

monitoring:
  check_interval: 60  # seconds
  alert_thresholds:
    drawdown: 0.03
    daily_loss: 0.01
    position_size: 0.05 